services:
  db:
    image: postgres:15
    container_name: fineasy
    environment:
      POSTGRES_USER: fineasy
      POSTGRES_PASSWORD: 40028922
      POSTGRES_DB: fineasy
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
